#%% Imports
import os
import argparse
import shutil
from glob import glob
import re


#%% Functions
### Note: These lists include files from previous versions of ReEDS
file_levels = {
    ## Scratch files
    0: [
        'inputs_case_original',
        os.path.join('inputs_case', 'load_hourly.h5'),
        os.path.join('inputs_case', r'^recf_.*\.h5$'),
        os.path.join('inputs_case', 'unitdata_orig.h5'),
        '225*',
    ],
    ## Intermediate input files and duplicates
    1: [
        os.path.join('inputs_case', 'csp.h5'),
        os.path.join('inputs_case', r'^temperature_.*\.h5$'),
        ## The following regex matches the outputs/*.csv files that are duplicates of data
        ## in outputs.h5. The exceptions are written by other scripts.
        os.path.join('outputs', r'^((?!(neue|eue|ra_metrics|health|h2_price_month)).)*csv$'),
    ],
    ## GAMS files. These are large and are not readable by the user, but the run cannot
    ## be restarted (and report.gms cannot be rerun) if they are deleted.
    2: [
        'g00files',
    ],
    ## Large input files: Would need to rerun input_processing to recreate
    ## Diagnostics plots: Can be regenerated by rerunning ra_calcs.py
    ## NOTE: Make sure your run is new enough to contain outputs/outputs.h5
    ## (Jan 2025 or later) before deleting outputs/rep_casename}.gdx
    3: [
        os.path.join('inputs_case', 'load.h5'),
        os.path.join('inputs_case', 'recf.h5'),
        os.path.join('inputs_case', 'outage_forced_hourly.h5'),
        os.path.join('inputs_case', 'outage_scheduled_hourly.h5'),
        os.path.join('inputs_case', 'dr_shed_hourly.h5'),
        os.path.join('inputs_case', 'inputs.gdx'),
        os.path.join('inputs_case', 'inputs_0.gdx'),
        os.path.join('inputs_case', 'rep', 'outage_forced_h.csv'),
        os.path.join('inputs_case', 'stress*i*', 'outage_forced_h.csv'),
        os.path.join('inputs_case', 'hydcf.csv'),
        os.path.join('inputs_case', 'unitdata.csv'),
        os.path.join('inputs_case', 'hintage_data.csv'),
        os.path.join('inputs_case', r'^supplycurve_.*\.csv$'),
        ## Diagnostic plots
        os.path.join('outputs', 'Augur_plots'),
        os.path.join('outputs', 'figures', 'resource_adequacy'),
        ## The outputs/rep_{casename}.gdx file written by report.gms
        ## contains the same data as outputs.h5
        os.path.join('outputs', r'^rep_.*\.gdx$'),
    ],
    ## Figures: Regenerate using single_case_plots.py
    4: [
        os.path.join('outputs', 'figures'),
        os.path.join('outputs', 'maps'),
        os.path.join('outputs', 'hourly'),
    ],
}


def delete(fpath, dryrun=0):
    if os.path.isdir(fpath):
        if dryrun:
            print(f'Would delete directory: {fpath}')
        else:
            shutil.rmtree(fpath)
    elif os.path.isfile(fpath):
        if dryrun:
            print(f'Would delete file: {fpath}')
        else:
            os.remove(fpath)


def delete_files(case, file_list, dryrun=0):
    """
    Deletes files in file_list from case
    (unless dryrun is True; then the files that would be deleted are printed instead)
    """
    for file in file_list:
        filepath = os.path.join(case, file)
        ## If it's a regex, delete the matches; otherwise, delete the whole thing
        if '*' in filepath:
            candidate_paths = sorted(glob(os.path.join(os.path.dirname(filepath), '*')))
            matched_paths = [
                i for i in candidate_paths
                if re.match(os.path.basename(filepath), os.path.basename(i))
            ]
            for f in matched_paths:
                delete(f, dryrun=dryrun)
        else:
            delete(filepath, dryrun=dryrun)


def parse_caselist(caselist):
    """Turn a list of globs into a flat list of filepaths"""
    outlist = []
    for caseprefix in caselist:
        outlist.extend(glob(caseprefix))
    return sorted(outlist)


def main(caselist, level=0, dryrun=0, force=0, quiet=0, file_levels=file_levels):
    """
    Deletes files specified by level and file_levels from cases in caselist

    Args:
        caselist (list): List of paths to ReEDS cases
        level (int): Level of file_levels up to which to delete files
        dryrun (bool): If True, print files but don't delete (default False)
        force (bool): If True, proceed without prompting user to confirm (default False)
        file_levels (dict): Map from level to list of filenames

    Returns:
        None
    """
    cases = parse_caselist(caselist)
    if not len(cases):
        print(f'No cases matching "{" ".join(caselist)}"')
        quit()

    file_list = sorted(
        sum([v for k,v in file_levels.items() if k <= level], [])
    )

    if not quiet:
        print('\nDeleting these files:')
        for f in file_list:
            print(f'- {f}')
        print('\nFrom these cases:')
        for c in cases:
            print(f'> {c}')
        if level >= 1:
            print(
                f'WARNING: cleanup level {level} removes files used by R2X, '
                'so do not proceed if you plan to run R2X.'
            )

    if not force:
        confirm = str(input('\nProceed? y/[n]: ') or 'n')
        if confirm.lower() not in ['y', 'yes', 'yeah', 'yup', '1', 'true']:
            quit()

    for case in cases:
        delete_files(case, file_list, dryrun=dryrun)


#%% Procedure
parser = argparse.ArgumentParser(
    description='Remove files from completed ReEDS cases',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)
parser.add_argument(
    'caselist',
    type=str,
    nargs='+',
    help=(
        'Path to a ReEDS case folder '
        'OR space-delimited list of case folders '
        'OR glob prefix (including *) for a group of case folders'
    ),
)
parser.add_argument(
    '--level',
    '-l',
    type=int,
    default=0,
    help='How aggressively to remove files (larger number = more files)',
)
parser.add_argument('--force', '-f', action='store_true', help='Proceed without double-checking')
parser.add_argument('--dryrun', '-d', action='store_true', help="Print files but don't delete")
parser.add_argument('--quiet', '-q', action='store_true', help="Don't print file/case lists")

args = parser.parse_args()
caselist = args.caselist
level = args.level
force = args.force
dryrun = args.dryrun
quiet = args.quiet

# #%% Inputs for testing
# caselist = [os.path.abspath(os.path.join('..', 'runs', 'v20250221_commonM2_Pacific'))]
# level = 0
# force = 0
# dryrun = 1
# quiet = 0

if __name__ == '__main__':
    main(caselist, level=level, dryrun=dryrun, force=force, quiet=quiet)
