'''Builds valcostfac_report.html: the value/cost-factor figures with the text and tables that carry
the argument, as one page.

Run after the figure modules, from run_report_valcostfac.py. It reads what they wrote into
output_dir - the csvs for numbers, the pngs for figures - and writes the report alongside them.

Figures are embedded as downscaled data URIs by default, so the page is a single self-contained
file that can be moved or sent on its own. Set embed_figures to False to reference the pngs by
relative filename instead, which keeps the html at a few tens of kB and the figures at full
resolution, at the cost of the page only working in place next to them. Either way the full-size
pngs stay in the directory for the paper.

The page carries figures, tables and descriptions of what each one plots - the quantities, how they
are constructed, what the axes and marks mean. It deliberately draws no conclusions and states no
findings: interpretation belongs with the analysis, not in a file regenerated by the pipeline, where
it would go stale silently the next time the runs change. Every number here is computed from the
csvs, so re-running restates it. Sections whose inputs are missing are skipped rather than raising,
so a partial report still renders if one of the figure modules was skipped.

Run this file on the reeds2 conda environment.
'''
import os
import numpy as np
import pandas as pd
from plcoe_pitch import (display_tech, load_full_range, vcf_matched_scale, vcf_panel_techs,
                         _fit_form, r2_y, load_style_colors, tech_style_path, normalize_tech_name,
                         years as table_years)
from report_switches import dollar_year

# User inputs
valcostfac_core_path = '/data/shared/projects/mmowers/ReEDS/postprocessing/bokehpivot/out/reeds_report/valcostfac_core.csv' #Only used when running this file standalone.
report_name = 'valcostfac_report.html' #Written into output_dir.
embed_figures = True #Embed each figure as a downscaled data URI, making the page self-contained and portable. False references the pngs by relative filename, which keeps the file small and the figures at full resolution but ties the page to this directory. Embedding needs Pillow; without it the report falls back to references and says so.
embed_max_width = 2600 #Pixels. Figures wider than this are downscaled before embedding; narrower ones are left alone. The by-year maps are the widest at about 4900px, and 2600 keeps their per-year panels legible.
decline_shares = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6] #Market shares tabulated in the cost-escalation decline table under the VCF figure.
embed_quality = 82 #JPEG quality for embedded figures. These are line charts and choropleths, where 82 is visually clean and roughly a fifth the size of the equivalent png.
report_title = 'Value-Cost Factor Figures' #Page title and headline.
vre_techs = ['Onshore Wind', 'UPV'] #Techs with per-tech map figures and rows in the suppression table. Names as they appear in valcostfac_core.csv, before display_tech.


def _num(x, fmt='{:.2f}', dash='&mdash;'):
    """Format a number for the page, or an em dash where it is missing."""
    return dash if x is None or (isinstance(x, float) and not np.isfinite(x)) else fmt.format(x)


def _swatch(tech, colors):
    c = colors.get(tech, '#888888')
    c = '#%02X%02X%02X' % tuple(int(v * 255) for v in c[:3]) if not isinstance(c, str) else c
    return f'<span class="sw" style="background:{c}"></span>'


def vcf_fit_table(df, techs=None):
    """Power-fit exponents per tech: the band width is k_vcf - k_vf, what figure 3 shades.

    techs overrides the default panel selection, for series that are not model technologies -
    the gas supply-curve pair, which is one technology under two price assumptions.
    """
    predict, _ = _fit_form('power')
    rows = []
    for tech in vcf_panel_techs(df, techs):
        d = df[df['tech'] == tech].dropna(
            subset=['gen_frac', 'value_factor', 'value_cost_factor'])
        matched = vcf_matched_scale(df, tech, 'power')
        if d.empty or matched is None:
            continue
        s, vf_p, vcf_p = matched
        x = d['gen_frac'].to_numpy()
        rows.append({
            'tech': tech, 'k_vf': vf_p[1], 'k_vcf': vcf_p[1], 'band': vcf_p[1] - vf_p[1],
            'r2': r2_y(d['value_factor'].to_numpy(), predict(vf_p, x)),
            'x_lo': x.min(), 'x_hi': x.max(),
            'cf_lo': d['cost_factor'].min(), 'cf_hi': d['cost_factor'].max(), 'n': len(d),
        })
    return pd.DataFrame(rows)


def cost_decline_table(fits):
    """1 - 1/CF at each tabulated market share, from the power fits.

    The fitted cost factor is the ratio of the two fits, and because the LCOE base scaling matched
    their intercepts the coefficients cancel, leaving (1-x)^(k_vcf - k_vf). So the decline in
    competitiveness attributable to cost is 1 - (1-x)^(k_vcf - k_vf) - zero at zero market share by
    construction, which is what makes the column an anchor rather than a measurement.

    Cells outside a technology's observed market-share range are flagged, not hidden: UPV's data
    ends at 0.45 and gas-CC's begins at 0.46, so a plain table would present reach and measurement
    at the same authority.
    """
    rows = []
    for _, r in fits.iterrows():
        cells = []
        for x in decline_shares:
            value = 1 - (1 - x) ** r['band'] if x < 1 else np.nan
            outside = x > 0 and (x < r['x_lo'] - 1e-9 or x > r['x_hi'] + 1e-9)
            cells.append((value, outside))
        rows.append({'tech': r['tech'], 'cells': cells})
    return rows


def rev_slopes(output_dir):
    """How much faster ReEDS marginal LCOE rises with generation than the reV supply curve."""
    path = os.path.join(output_dir, 'reeds_vs_rev.csv')
    if not os.path.exists(path):
        return pd.DataFrame()
    r = pd.read_csv(path)
    rows = []
    for tech, g in r.groupby('tech'):
        g = g.sort_values('gen_twh')
        if len(g) < 2:
            continue
        slope = lambda col: np.polyfit(g['gen_twh'], g[col], 1)[0] * 1000
        rv, rd = slope('rev_lcoe'), slope('reeds_lcoe_cost_factor')
        rows.append({'tech': tech, 'rev_slope': rv, 'reeds_slope': rd,
                     'ratio': rd / rv if rv else np.nan,
                     'rev_escal': g['rev_lcoe'].iloc[-1] / g['rev_lcoe'].iloc[0],
                     'reeds_escal': (g['reeds_lcoe_cost_factor'].iloc[-1]
                                     / g['reeds_lcoe_cost_factor'].iloc[0])})
    return pd.DataFrame(rows)


def cost_shares(output_dir):
    """Cost's share of the total log decline in competitiveness, at each tech's highest share."""
    path = os.path.join(output_dir, 'plcoe_pitch_vcf_decomposition.csv')
    if not os.path.exists(path):
        return pd.DataFrame()
    d = pd.read_csv(path)
    rows = []
    for tech, g in d.groupby('tech'):
        g = g.sort_values('gen_frac')
        rows.append({'tech': tech, 'gen_frac': g['gen_frac'].iloc[-1],
                     'cost_share': g['cost_share'].iloc[-1],
                     'total_decline': g['total_decline'].iloc[-1]})
    return pd.DataFrame(rows)


def composition_shares(output_dir):
    """Regional mix effect against the total cost-factor rise, early window to late window."""
    path = os.path.join(output_dir, 'spatial_value_cost_decomp.csv')
    if not os.path.exists(path):
        return pd.DataFrame()
    d = pd.read_csv(path)
    rows = []
    for tech, g in d.groupby('tech'):
        g = g.sort_values('t')
        early, late = g.head(4), g.tail(3)
        rows.append({'tech': tech,
                     'actual': late['actual'].mean() / early['actual'].mean(),
                     'compos': late['compos'].mean() / early['compos'].mean(),
                     't_lo': int(g['t'].min()), 't_hi': int(g['t'].max())})
    return pd.DataFrame(rows)


def read_csv_or_empty(output_dir, name):
    path = os.path.join(output_dir, name)
    return pd.read_csv(path) if os.path.exists(path) else pd.DataFrame()


CSS = '''
:root{
  --paper:#F4F7F9; --raise:#FFFFFF; --ink:#111A20; --body:#22313B; --muted:#54697A;
  --rule:#D7E1E8; --rule-soft:#E6EDF1; --accent:#0092C0;
}
@media (prefers-color-scheme:dark){
  :root:not([data-theme="light"]){
    --paper:#0C1317; --raise:#131E24; --ink:#EAF2F6; --body:#C3D2DA; --muted:#8AA2B0;
    --rule:#22333C; --rule-soft:#1A272E; --accent:#33C6F5;
  }
}
:root[data-theme="dark"]{
  --paper:#0C1317; --raise:#131E24; --ink:#EAF2F6; --body:#C3D2DA; --muted:#8AA2B0;
  --rule:#22333C; --rule-soft:#1A272E; --accent:#33C6F5;
}
*{box-sizing:border-box}
body{background:var(--paper);color:var(--body);
  font-family:"Source Serif 4",Georgia,"Times New Roman",serif;
  font-size:17px;line-height:1.62;-webkit-font-smoothing:antialiased;
  padding-block:0 5rem;padding-left:20px;padding-right:20px;margin:0;}
.wrap{max-width:1180px;margin:0 auto;}
.col{max-width:68ch;}
h1,h2,h3,.lbl,th,.fignum{font-family:"IBM Plex Sans",system-ui,-apple-system,sans-serif;}
.lbl,.fignum,.mono,td.num,th.num,.meta{font-family:"IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,monospace;}
h1{font-size:clamp(2.1rem,5.2vw,3.3rem);line-height:1.06;letter-spacing:-.022em;font-weight:700;
   color:var(--ink);margin:.6rem 0 0;text-wrap:balance;}
h2{font-size:1.42rem;line-height:1.22;letter-spacing:-.012em;font-weight:600;color:var(--ink);
   margin:0;text-wrap:balance;}
h3{font-size:1.02rem;font-weight:600;color:var(--ink);margin:1.7rem 0 .1rem;}
p{margin:0;} a{color:var(--accent);}
.col p + p{margin-top:.9rem;}
.lbl{font-size:.685rem;letter-spacing:.13em;text-transform:uppercase;color:var(--muted);font-weight:500;}
header{padding-block:3.4rem 2.2rem;border-bottom:2px solid var(--ink);}
.stand{font-size:1.2rem;line-height:1.5;margin-top:1.1rem;max-width:62ch;}
.meta{font-size:.75rem;color:var(--muted);margin-top:1.6rem;display:flex;flex-wrap:wrap;gap:.45rem 1.4rem;}
section{padding-block:3.2rem;border-bottom:1px solid var(--rule-soft);}
.shead{display:flex;gap:1rem;align-items:baseline;margin-bottom:1.15rem;}
.snum{font-family:"IBM Plex Mono",monospace;font-size:.8rem;font-weight:500;color:var(--accent);
  padding-top:.16rem;flex:none;}
figure{margin:2rem 0 0;}
figure img{display:block;width:100%;max-width:100%;height:auto;border:1px solid var(--rule);
  background:#fff;border-radius:2px;}
figcaption{display:grid;grid-template-columns:auto 1fr;gap:.55rem 1rem;margin-top:.8rem;
  font-size:.87rem;line-height:1.5;color:var(--muted);align-items:baseline;}
.fignum{font-size:.7rem;letter-spacing:.08em;color:var(--accent);text-transform:uppercase;
  white-space:nowrap;padding-top:.12rem;}
figcaption b{color:var(--ink);font-weight:600;font-family:"IBM Plex Sans",sans-serif;}
.tw{overflow-x:auto;margin-top:1.7rem;border:1px solid var(--rule);background:var(--raise);}
table{border-collapse:collapse;width:100%;font-size:.85rem;
  font-family:"IBM Plex Sans",system-ui,sans-serif;}
caption{text-align:left;font-family:"IBM Plex Mono",monospace;font-size:.7rem;
  letter-spacing:.08em;text-transform:uppercase;color:var(--muted);padding:.85rem 1rem .1rem;}
th,td{padding:.5rem .85rem;text-align:left;border-bottom:1px solid var(--rule-soft);white-space:nowrap;}
thead th{font-size:.7rem;letter-spacing:.045em;text-transform:uppercase;color:var(--muted);
  font-weight:600;border-bottom:1px solid var(--rule);}
tbody tr:last-child td{border-bottom:none;}
td.num,th.num{text-align:right;font-variant-numeric:tabular-nums;
  font-family:"IBM Plex Mono",monospace;}
td.t{font-weight:600;color:var(--ink);}
td.out{color:var(--muted);opacity:.62;}
.sw{display:inline-block;width:9px;height:9px;border-radius:2px;margin-right:.5rem;}
.sub{color:var(--muted);font-size:.78em;}
.eq{font-family:"IBM Plex Mono",monospace;font-size:.93em;color:var(--ink);
  background:var(--rule-soft);padding:.08em .38em;border-radius:3px;}
footer{padding-top:2.6rem;font-size:.8rem;color:var(--muted);}
footer code{font-family:"IBM Plex Mono",monospace;font-size:.95em;}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
'''


def embed_source(path):
    """A data URI for one figure, downscaled to embed_max_width.

    Returns None if Pillow is unavailable, so the caller can fall back to a relative reference
    rather than the report failing over a packaging choice.
    """
    try:
        from PIL import Image
    except ImportError:
        return None
    import base64
    import io
    with Image.open(path) as im:
        im = im.convert('RGB')
        if im.width > embed_max_width:
            height = round(im.height * embed_max_width / im.width)
            im = im.resize((embed_max_width, height), Image.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, 'JPEG', quality=embed_quality, optimize=True, progressive=True)
    return 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode()


def figure(output_dir, filename, num, title, body, order):
    """One figure block, or nothing if that png was not produced.

    body describes what the figure plots - axes, marks, construction - and stops there.
    """
    path = os.path.join(output_dir, filename)
    if not os.path.exists(path):
        return ''
    src = embed_source(path) if embed_figures else None
    if embed_figures and src is None:
        order.append(('fallback', filename))
    src = src or filename
    order.append(filename)
    return (f'<figure><img src="{src}" alt="{title}">'
            f'<figcaption><span class="fignum">Fig {num}</span>'
            f'<span><b>{title}</b> {body}</span></figcaption></figure>')


def table(caption, headers, rows):
    """A table block. headers is a list of (label, is_numeric)."""
    if not rows:
        return ''
    cells = []
    for lbl, is_num in headers:
        cls = ' class="num"' if is_num else ''
        cells.append(f'<th{cls}>{lbl}</th>')
    head = ''.join(cells)
    return (f'<div class="tw"><table><caption>{caption}</caption>'
            f'<thead><tr>{head}</tr></thead><tbody>{"".join(rows)}</tbody></table></div>')


def build_html(output_dir, core_path):
    """Assemble the page from whatever the figure modules left in output_dir."""
    core = pd.read_csv(core_path)
    df = load_full_range(core_path, core)
    colors = load_style_colors(tech_style_path)
    colors = {t: colors.get(normalize_tech_name(t), '#888888') for t in core['tech'].unique()}

    fits = vcf_fit_table(df)
    rev = rev_slopes(output_dir)
    shares = cost_shares(output_dir)
    comp = composition_shares(output_dir)
    scope = read_csv_or_empty(output_dir, 'spatial_value_scope_fit.csv')
    supp = read_csv_or_empty(output_dir, 'spatial_value_stats.csv')
    align = read_csv_or_empty(output_dir, 'spatial_value_alignment.csv')
    lvoe = read_csv_or_empty(output_dir, 'lvoe_vs_lcoe.csv')

    vre = [t for t in vre_techs if t in set(core['tech'])]
    order = []
    tech_cell = lambda t: f'<td class="t">{_swatch(t, colors)}{display_tech(t)}</td>'

    # ---- 01 ReEDS against the reV supply curve ----
    fig1 = figure(output_dir, 'reeds_vs_rev_cost-factor.png', 1,
                  'ReEDS marginal LCOE and the reV supply curve.',
                  'x is cumulative annual generation in TWh. Grey is the reV supply curve, drawn '
                  'from the supply curve file and sampled at the ReEDS generation levels for its '
                  f'fit; coloured is the ReEDS marginal LCOE re-based onto the LCOE base year by '
                  f'multiplying by the cost factor. Dotted lines are least-squares fits over the '
                  f'ReEDS range. Both axes in {dollar_year}$/MWh.', order)
    rev_rows = [
        f'<tr>{tech_cell(r["tech"])}'
        f'<td class="num">{_num(r["rev_slope"], "{:.1f}")}</td>'
        f'<td class="num">{_num(r["reeds_slope"], "{:.1f}")}</td>'
        f'<td class="num">{_num(r["ratio"], "{:.1f}")}</td>'
        f'<td class="num">{_num(r["rev_escal"], "{:.2f}")}</td>'
        f'<td class="num">{_num(r["reeds_escal"], "{:.2f}")}</td></tr>'
        for _, r in rev.iterrows()] if not rev.empty else []
    rev_table = table(
        f'Fitted slopes over the ReEDS generation range, {dollar_year}$/MWh per 1000 TWh',
        [('Technology', False), ('reV slope', True), ('ReEDS slope', True), ('Ratio', True),
         ('reV escalation', True), ('ReEDS escalation', True)], rev_rows)

    fig1b = figure(output_dir, 'reeds_vs_rev_curtailment.png', 2,
                   'The same comparison on consistent curtailment bases.',
                   'The cost-factor re-basing drawn twice. Pre-curtailment keeps the LVOE-based '
                   'cost, which is per uncurtailed MWh, and puts it against uncurtailed generation '
                   'from gen_ivrt_uncurt; the reV curve is sampled on the same basis, as its LCOE '
                   'is built on nominal capacity factors. Post-curtailment keeps actual generation '
                   'and divides the same cost by one minus the curtailment fraction, giving cost '
                   'per delivered MWh. The figure above is a mix of the two: cost per uncurtailed '
                   'MWh against post-curtailment TWh.', order)
    curt_rows = []
    curt_path = os.path.join(output_dir, 'reeds_vs_rev.csv')
    if os.path.exists(curt_path):
        rc = pd.read_csv(curt_path)
        if 'curtailment' in rc:
            for tech, g in rc.groupby('tech'):
                g = g.sort_values('year')
                last = g.iloc[-1]
                curt_rows.append(
                    f'<tr>{tech_cell(tech)}'
                    f'<td class="num">{int(last["year"])}</td>'
                    f'<td class="num">{_num(last["gen_pre_twh"], "{:.0f}")}</td>'
                    f'<td class="num">{_num(last["gen_post_twh"], "{:.0f}")}</td>'
                    f'<td class="num">{last["curtailment"]:.1%}</td>'
                    f'<td class="num">{_num(last["reeds_lcoe_cost_factor"], "{:.1f}")}</td>'
                    f'<td class="num">{_num(last["lcoe_cf_post"], "{:.1f}")}</td></tr>')
    curt_table = table(
        f'Generation bases and cost at the last modelled year, {dollar_year}$/MWh',
        [('Technology', False), ('Year', True), ('Pre-curtailment TWh', True),
         ('Post-curtailment TWh', True), ('Curtailment', True), ('Cost, pre', True),
         ('Cost, post', True)], curt_rows)

    # ---- 02 value factor and value-cost factor ----
    fig2 = figure(output_dir, 'plcoe_pitch_VCF_power_synced.png', 3,
                  'Value factor and value&#8211;cost factor against market share.',
                  'One panel per technology, all on one pair of axis ranges. LCOE base is scaled '
                  'per technology until the two power fits share an intercept at zero market share; '
                  'the shaded band is the area between the fits after that scaling. The grey series '
                  'is the reciprocal of the cost factor, with the dotted grey curve the ratio '
                  'implied by the two fits. Curves stop where each technology&rsquo;s data stops.',
                  order)
    fit_rows = [
        f'<tr>{tech_cell(r["tech"])}'
        f'<td class="num">{_num(r["k_vf"])}</td><td class="num">{_num(r["k_vcf"])}</td>'
        f'<td class="num">{_num(r["band"])}</td><td class="num">{_num(r["r2"])}</td>'
        f'<td class="num">{r["x_lo"]:.2f}&#8211;{r["x_hi"]:.2f}</td>'
        f'<td class="num">{r["cf_lo"]:.2f}&#8211;{r["cf_hi"]:.2f}</td>'
        f'<td class="num">{int(r["n"])}</td></tr>'
        for _, r in fits.sort_values('band', ascending=False).iterrows()] if not fits.empty else []
    decline_rows = []
    for r in cost_decline_table(fits.sort_values('band', ascending=False)) if not fits.empty else []:
        cells = ''.join(
            f'<td class="num{" out" if outside else ""}">{_num(v, "{:.1%}")}</td>'
            for v, outside in r['cells'])
        decline_rows.append(f'<tr>{tech_cell(r["tech"])}{cells}</tr>')
    decline_table = table(
        'Competitiveness decline from cost escalation, 1 &minus; 1/CF from the power fits. '
        'Zero at zero market share by construction; muted cells are outside that '
        'technology&rsquo;s observed range',
        [('Technology', False)] + [(f'{x:.0%}', True) for x in decline_shares], decline_rows)

    fig2b = figure(output_dir, 'plcoe_pitch_VCF_power_synced_postcurt.png', 4,
                   'The same figure with VRE per MWh generated.',
                   'A sensitivity on the energy basis. Above, wind and UPV value and cost are per '
                   'uncurtailed MWh, the basis of LVOE in valnew, while the dispatchable technologies '
                   'are per MWh dispatched; here every technology is per MWh actually generated. '
                   'Value factor and cost factor each scale by one over one minus the curtailment of '
                   'that year&rsquo;s new builds, taken over the invested vintages from gen_ivrt and '
                   'gen_ivrt_uncurt, and the value&#8211;cost factor is unchanged because the '
                   'multiplier cancels in the ratio. Only the split between value and cost moves. '
                   'New-build curtailment is well above fleet curtailment, since the marginal unit '
                   'is built into an already saturated region.', order)

    fig2c = figure(output_dir, 'plcoe_pitch_VCF_power_synced_avail.png', 5,
                   'The same figure with every technology per MWh available.',
                   'The mirror of the sensitivity above. That one resolves the mixed default basis '
                   'by putting every technology per MWh generated; this one resolves it the other '
                   'way, per MWh available. Available energy is the right-hand side of the capacity '
                   'limit in both cases: the resource, m_cf times capacity, for wind and UPV, and '
                   'capacity derated for forced and planned outages for the rest. Value factor and '
                   'cost factor scale together so the value&#8211;cost factor is again unchanged. '
                   'Read the dispatchable panels with care, for two reasons. Unused availability for a '
                   'peaking plant is capacity held for scarcity rather than output nobody wanted, '
                   'so a low value here does not carry the meaning it carries for VRE. And as a '
                   'dispatchable technology takes a larger share it has to cover peakier parts of '
                   'the load duration curve, so its marginal build runs at a lower capacity factor '
                   'and delivered over available falls with market share &mdash; from 1.01 to 0.76 '
                   'for nuclear across the horizon. Both value and cost per available MWh therefore '
                   'fall faster with market share than they otherwise would, which is what turns '
                   'the fitted cost escalation slightly negative for these technologies. That is a '
                   'statement about utilization, not about resource quality.', order)

    fit_table = table(
        'Power fits, y = A(1-x)^k, over the full market-share range',
        [('Technology', False), ('k<sub>VF</sub>', True), ('k<sub>VCF</sub>', True),
         ('k<sub>VCF</sub> &minus; k<sub>VF</sub>', True), ('R&sup2; of VF fit', True),
         ('Market share', True), ('Cost factor', True), ('n', True)], fit_rows)

    # ---- 02b storage, held out of the shared-axes figure ----
    stor_fig = figure(output_dir, 'plcoe_pitch_VCF_power_storage.png', 6,
                      'Value factor and value&#8211;cost factor for storage.',
                      'The same construction as the figure above, drawn by the same function, for '
                      'the technologies held out of it. Storage occupies a different part of the '
                      'plane &mdash; value factor above one at low market share, and a market share '
                      'that stops near 15% &mdash; so sharing a pair of axis ranges with it '
                      'compresses every other panel. The grey series is the reciprocal of the cost '
                      'factor and the dotted grey curve is the ratio the two fits imply; for '
                      'storage those two part company completely, and the R&sup2; of the implied '
                      'curve against the data it is drawn over is negative, so the shaded band here '
                      'does not describe the cost-factor data.', order)

    dur_fig = figure(output_dir, 'plcoe_pitch_storage_duration.png', 7,
                     'Duration of new storage builds by model year.',
                     'Duration is the energy capacity a build adds divided by the power capacity '
                     'it adds, <span class="eq">INV_ENERGY / INV</span>, read from '
                     'cap_energy_new_out and cap_new_ivrt. One box per model year over the '
                     'regional builds of that year. Boxes and the connected mean are '
                     'capacity-weighted, so a region adding a gigawatt counts for more than one '
                     'adding ten megawatts, and box width is proportional to the square root of '
                     'the capacity built that year. Whiskers are the weighted 10th and 90th '
                     'percentiles. Years adding less than a gigawatt are omitted. Power and energy '
                     'are separate decision variables in ReEDS, so a build can add energy to '
                     'existing power capacity or the reverse; differencing cumulative energy '
                     'capacity instead would mix those cases together with retirements.', order)
    dur_df = read_csv_or_empty(output_dir, 'plcoe_pitch_storage_duration.csv')
    dur_rows = []
    if not dur_df.empty:
        for _, r in dur_df[dur_df['year'].isin(table_years)].iterrows():
            dur_rows.append(
                f'<tr><td class="t">{int(r["year"])}</td>'
                f'<td class="num">{_num(r["gw"], "{:.1f}")}</td>'
                f'<td class="num">{int(r["n_regions"])}</td>'
                f'<td class="num">{_num(r["p25"])}</td>'
                f'<td class="num">{_num(r["median"])}</td>'
                f'<td class="num">{_num(r["p75"])}</td>'
                f'<td class="num">{_num(r["mean"])}</td></tr>')
    dur_table = table(
        'New storage duration at the headline years, capacity-weighted, hours',
        [('Year', False), ('Built, GW', True), ('Regions', True), ('p25', True),
         ('Median', True), ('p75', True), ('Mean', True)], dur_rows)

    # ---- 02c gas against the national gas supply curve ----
    gas_fuel_fig = figure(output_dir, 'gas_supply_curve_fuel.png', 8,
                          'Fuel cost a new Gas-CC would face under the national gas supply curve.',
                          'nat_beta times the run&rsquo;s electric-sector gas burn above the AEO '
                          'reference, converted at the new-build heat rate. Labels give the burn '
                          'against that reference at each end. Only the national term of the supply '
                          'curve is applied: the census-division term is omitted because re-siting '
                          'would partly avoid it, while the national one can only be avoided by '
                          'building less gas.', order)
    gas_fig = figure(output_dir, 'gas_supply_curve_vcf.png', 9,
                     'Value factor and value&#8211;cost factor for Gas-CC, static against '
                     'supply-curve gas.',
                     'The construction of the figure in section 02, drawn by the same function, '
                     'with the solved run and the corrected series as the two panels. Left is what '
                     'the model solved with static gas prices; right adds the fuel cost at left to '
                     'the cost factor, holding the value factor at its modelled level so the whole '
                     'increase falls on cost. The shaded band is the area between the two fits after '
                     'the intercepts are matched, so its width is the cost escalation. Across the '
                     'four curve options the added fuel cost at the last model year spans 20.1 to '
                     '27.8 2024$/MWh; the functional form matters more than the geographic scope, '
                     'since the power-law option sits above all three linear ones.', order)
    #The same competitiveness-decline table as section 02, over the two gas series. The two
    #differ only in the cost factor, so the value-factor exponent is common and the whole gap
    #between the rows is cost escalation the static-price run does not see.
    gas_decline_rows = []
    gas_pairs = read_csv_or_empty(output_dir, 'gas_supply_curve_pairs.csv')
    if not gas_pairs.empty:
        gas_fits = vcf_fit_table(gas_pairs, techs=sorted(gas_pairs['tech'].unique()))
        for r in cost_decline_table(gas_fits.sort_values('band')):
            cells = ''.join(
                f'<td class="num{" out" if outside else ""}">{_num(v, "{:.1%}")}</td>'
                for v, outside in r['cells'])
            gas_decline_rows.append(f'<tr><td class="t">{r["tech"]}</td>{cells}</tr>')
    gas_decline_table = table(
        'Competitiveness decline from cost escalation for Gas-CC, 1 &minus; 1/CF from the power '
        'fits, with and without the gas supply curve. Muted cells are outside the observed '
        'market-share range',
        [('Series', False)] + [(f'{x:.0%}', True) for x in decline_shares], gas_decline_rows)

    gas_rows = []
    if os.path.exists(os.path.join(output_dir, 'gas_supply_curve.csv')):
        gdf = pd.read_csv(os.path.join(output_dir, 'gas_supply_curve.csv'))
        for _, r in gdf.iterrows():
            gas_rows.append(
                f'<tr><td class="t">{int(r["year"])}</td>'
                f'<td class="num">{_num(r["gen_frac"], "{:.2f}")}</td>'
                f'<td class="num">{_num(r["burn_quads"], "{:.1f}")}</td>'
                f'<td class="num">{_num(r["dq_quads"], "{:+.1f}")}</td>'
                f'<td class="num">{_num(r["dcost_usd_per_mwh"], "{:.1f}")}</td>'
                f'<td class="num">{_num(r["cost_factor_static"])}</td>'
                f'<td class="num">{_num(r["cost_factor_corrected"])}</td>'
                f'<td class="num">{_num(r["value_cost_factor_static"])}</td>'
                f'<td class="num">{_num(r["value_cost_factor_corrected"])}</td></tr>')
    gas_table = table(
        f'Gas-CC with and without the national gas supply curve, {dollar_year}$/MWh',
        [('Year', False), ('Market share', True), ('Electric gas burn, Quads', True),
         ('vs AEO reference', True), ('Added fuel cost', True), ('Cost factor, static', True),
         ('Cost factor, corrected', True), ('VCF, static', True), ('VCF, corrected', True)],
        gas_rows)

    # ---- 02d capacity credit ----
    cc_fig = figure(output_dir, 'plcoe_pitch_capacity_credit.png', 10,
                    'Capacity credit of new builds against market share.',
                    'For each year&rsquo;s new builds, the reserve-margin value they earned divided '
                    'by what the same capacity would have earned in the same regions had it been '
                    'available in every stress hour: '
                    '<span class="eq">&Sigma;<sub>r</sub> val_resmarg / '
                    '&Sigma;<sub>r</sub> MW &middot; res_marg_ann</span>, where res_marg_ann is the '
                    'sum of a region&rsquo;s stress-hour reserve-margin prices. Both sums run over '
                    'regions before the division, matching how the regional quantity is itself '
                    'built: report.gms forms val_resmarg as a sum over stress hours of firm '
                    'contribution times that hour&rsquo;s price, so the number is price-weighted at '
                    'every level. Because those prices are concentrated in a few hours, this sits '
                    'below an hour-counting ELCC for resource-limited technologies. Storage is net '
                    'of charging, so its credit is a round-trip-net quantity.', order)
    cc_cap_fig = figure(output_dir, 'plcoe_pitch_capacity_credit_cap.png', 11,
                        'The same capacity credits against cumulative installed capacity.',
                        'Identical data to the figure above on a different x axis: the cumulative '
                        'national capacity of that technology in its own forcing run, on a log '
                        'scale because the technologies span twenty gigawatts to three terawatts. '
                        'Market share and installed capacity order the technologies differently, '
                        'since a gigawatt of storage and a gigawatt of wind are nowhere near the '
                        'same share of generation; against capacity the resource-limited '
                        'technologies fall along visibly separate paths rather than overlapping.', order)
    cc_sc_fig = figure(output_dir, 'plcoe_pitch_capacity_credit_scenarios.png', 12,
                       'Capacity credit of new storage and UPV in every scenario.',
                       'The capacity credit above, computed the same way, for new builds of '
                       'storage and UPV in each run rather than only in the run that forces them. '
                       'Rows are the technology; the left column is against model year and the '
                       'right against that technology&rsquo;s own installed national capacity in '
                       'the run, on a log scale. Each scenario takes the colour of the technology '
                       'it forces and has its own marker; the reference run, which forces nothing, '
                       'is dashed grey. A year in which the run added under a gigawatt of the '
                       'technology is left out, since the credit of a few hundred megawatts '
                       'depends on which one or two regions happened to build, and lines break '
                       'across the omitted years. If a technology&rsquo;s credit depended only on '
                       'how much of it is installed, every scenario would fall on one curve in '
                       'the right column.', order)
    cc_sc = read_csv_or_empty(output_dir, 'plcoe_pitch_capacity_credit_scenarios.csv')
    cc_sc_rows, cc_sc_cols = [], []
    if not cc_sc.empty:
        #The csv is written in scenarios-file order, so its own first-appearance order is that order
        #and the report needs no path to the scenarios file.
        sc_order = list(cc_sc['scenario'].drop_duplicates())
        cc_sc_cols = [(t, y) for t in [t for t in ('Battery', 'UPV') if t in set(cc_sc['tech'])]
                      for y in table_years]
        lookup = cc_sc.set_index(['scenario', 'tech', 'year'])['capacity_credit']
        for sc in sc_order:
            ft = cc_sc.loc[cc_sc['scenario'] == sc, 'forced_tech'].iloc[0]
            label = 'Reference (no forcing)' if pd.isna(ft) else f'{display_tech(ft)} forced'
            cells = ''.join(f'<td class="num">{_num(lookup.get((sc, t, y), np.nan), "{:.2f}")}</td>'
                            for t, y in cc_sc_cols)
            cc_sc_rows.append(f'<tr><td class="t">{label}</td>{cells}</tr>')
    cc_sc_table = table(
        'Capacity credit of new storage and UPV by scenario at the headline years. A dash is a '
        'year in which the run added under a gigawatt of that technology',
        [('Scenario', False)] + [(f'{display_tech(t)} {y}', True) for t, y in cc_sc_cols],
        cc_sc_rows)
    cc_df = read_csv_or_empty(output_dir, 'plcoe_pitch_capacity_credit.csv')
    cc_rows, cc_years = [], []
    if not cc_df.empty:
        #The figure carries the whole trajectory; the table gives anchor values at the
        #report's headline years, since one column per model year runs to thirteen.
        cc_years = [y for y in table_years if y in set(cc_df['year'])]
        wide = cc_df.pivot_table(index='tech', columns='year', values='capacity_credit')
        share = cc_df.pivot_table(index='tech', columns='year', values='gen_frac')
        for tech in wide.index:
            cells = ''.join(
                f'<td class="num">{_num(wide.loc[tech, y], "{:.3f}")}'
                + (f'<span class="sub"> {share.loc[tech, y]:.0%}</span>'
                   if pd.notna(share.loc[tech, y]) else '') + '</td>'
                for y in cc_years)
            cc_rows.append(f'<tr>{tech_cell(tech)}{cells}</tr>')
    cc_table = table(
        'Capacity credit of each year&rsquo;s new builds, with that technology&rsquo;s market '
        'share in small type beside it',
        [('Technology', False)] + [(str(int(y)), True) for y in cc_years], cc_rows)

    arb_df = read_csv_or_empty(output_dir, 'plcoe_pitch_storage_arbitrage.csv')
    #Block length as the run had it, so the caption follows a change of stress resolution.
    blk = (f'{arb_df["block_hours"].iloc[0]:g}'
           if not arb_df.empty and 'block_hours' in arb_df else 'GSw_HourlyChunkLengthStress')
    arb_fig = figure(output_dir, 'plcoe_pitch_storage_arbitrage.png', 13,
                     'How storage earns its reserve-margin value inside the stress periods.',
                     'Left: the reserve-margin price of each stress block, weighted by the '
                     'storage fleet&rsquo;s discharge and by its charging, on a log scale. ReEDS '
                     'reports these prices per MW per block, since the blocks carry no weight in '
                     f'the annual objective; each block is {blk} hours long '
                     f'(GSw_HourlyChunkLengthStress), so a MW held through it is {blk} MWh, and the '
                     'price per MW divided by the block length is the value of a MWh delivered in '
                     'that block. The price levels depend on the block length: re-cutting the stress '
                     'periods holds this per-MWh price roughly fixed where a long stretch of blocks '
                     'binds, but not where one peak block carries most of the day&rsquo;s value, '
                     'which then keeps its price per MW instead. The ratio of the two prices and '
                     'the credit shares at right do not carry the unit. '
                     'with the span between them shaded. Right: the same years split into the '
                     'gross value of discharge and the cost of charging, whose sum is the net '
                     'capacity credit of the whole storage fleet in every region. The figures above '
                     'are each year&rsquo;s new builds instead; for storage the two differ only in '
                     'which regions count, because every battery past the initial fleet shares one '
                     'vintage and valnew credits a new build with that vintage&rsquo;s dispatch '
                     'pro-rated by INV/CAP. gen_h_stress is already net of '
                     'charging for storage, so a negative entry is a charging hour. Net energy '
                     'over a stress period is zero or slightly negative for storage &mdash; it '
                     'discharges only what it charged, less round-trip losses &mdash; so the whole '
                     'of the capacity credit is the spread between these two prices.', order)
    arb_rows = []
    for _, r in arb_df.iterrows():
        arb_rows.append(
            f'<tr><td class="t">{int(r["year"])}</td>'
            f'<td class="num">{_num(r["gw"], "{:.0f}")}</td>'
            f'<td class="num">{_num(r["price_discharge"], "{:,.0f}")}</td>'
            f'<td class="num">{_num(r["price_charge"], "{:,.0f}")}</td>'
            f'<td class="num">{_num(r["gross"], "{:.3f}")}</td>'
            f'<td class="num">{_num(r["charge_cost"], "{:.3f}")}</td>'
            f'<td class="num">{_num(r["net"], "{:.3f}")}</td></tr>')
    arb_table = table(
        f'Storage stress-period arbitrage by model year. Prices are {dollar_year}$/MWh delivered in '
        'a stress block; the last '
        'three columns are shares of fully-firm capacity value and the first two of them sum to '
        'the third',
        [('Year', False), ('Fleet GW', True), ('Discharge price', True), ('Charge price', True),
         ('Gross', True), ('Charging cost', True), ('Fleet net credit', True)], arb_rows)

    # ---- 03 log decomposition ----
    fig3 = figure(output_dir, 'plcoe_pitch_VRE_VCF_decomposition.png', 14,
                  'Log decline in value&#8211;cost factor, split into value and cost parts.',
                  'Bar height is &minus;ln(VCF) at that market share, the total log decline. The '
                  'two segments are &minus;ln(VF) and &minus;ln(1/CF), which sum to it exactly. '
                  'Percentages on the bars are the cost segment as a share of the total.', order)
    share_rows = [
        f'<tr>{tech_cell(r["tech"])}'
        f'<td class="num">{r["gen_frac"]:.3f}</td>'
        f'<td class="num">{_num(r["total_decline"])}</td>'
        f'<td class="num">{r["cost_share"]:.0%}</td></tr>'
        for _, r in shares.iterrows()] if not shares.empty else []
    share_table = table(
        'Log decomposition at each technology&rsquo;s highest market share',
        [('Technology', False), ('Market share', True), ('Total -ln(VCF)', True),
         ('Cost share', True)], share_rows)

    # ---- 04 maps ----
    map_figs, n = '', 15
    for tech in vre:
        slug = display_tech(tech).lower().replace(' ', '-')
        block = figure(
            output_dir, f'spatial_value_map_byyear_{slug}.png', n,
            f'{display_tech(tech)} by model year.',
            'Columns are model years. Rows are: fleet value factor and new-build value factor, both '
            'divided by the national fleet value factor of the same year and sharing one diverging '
            'scale centred on 1; penetration (uncurtailed generation over regional load) for the '
            'region and for its transmission region, on one shared scale; cumulative capacity in '
            'GW on a single scale across years; new capacity that year, scaled within the year; and '
            'regional market share. Grey is no capacity, or no build that year in the new-build '
            'rows. Capacity and penetration ramps are linear with the top decile saturating. '
            'National values are annotated in each panel.', order)
        if block:
            map_figs += block
            n += 1

    # ---- 05 value factor against penetration ----
    fig_supp = figure(output_dir, 'spatial_value_suppression.png', n,
                      'Regional value factor against penetration.',
                      'One dot per region-year, sized by generation. Year means are removed from '
                      'both axes, leaving cross-regional variation. Rows are the total value '
                      'factor, the value factor on energy revenue alone, and the local energy price '
                      'relative to the national price. Dashed lines are the year-fixed-effect fits '
                      'whose slopes are quoted on each panel.', order)
    n += 1 if fig_supp else 0

    supp_rows = []
    if not supp.empty:
        techs_s = [t for t in vre if t in set(supp['tech'])]
        supp_head = [('Measure', False)]
        for t in techs_s:
            supp_head += [(f'{display_tech(t)}, year FE', True), ('+ region FE', True)]
        for key, label in [('ln_vf', 'ln(value factor)'),
                           ('ln_vf_energy', 'ln(energy-only value factor)'),
                           ('ln_price_energy_rel', 'ln(local energy price / national)'),
                           ('ln_price_rel', 'ln(local benchmark / national)')]:
            cells = ''
            for t in techs_s:
                row = supp[(supp['tech'] == t) & (supp['metric'] == key)]
                a = row['slope_year_fe'].iloc[0] if not row.empty else np.nan
                b = row['slope_region_fe'].iloc[0] if not row.empty else np.nan
                cells += (f'<td class="num">{_num(a, "{:+.3f}")}</td>'
                          f'<td class="num">{_num(b, "{:+.3f}")}</td>')
            supp_rows.append(f'<tr><td>{label}</td>{cells}</tr>')
    else:
        supp_head = [('Measure', False)]
    supp_table = table('Slope of each measure on penetration, per unit of penetration',
                       supp_head, supp_rows)

    scope_rows = [
        f'<tr>{tech_cell(r["tech"])}'
        f'<td class="num">{_num(r["slope_own"], "{:+.3f}")}</td>'
        f'<td class="num">{_num(r["slope_transreg"], "{:+.3f}")}</td>'
        f'<td class="num">{_num(r["r2"])}</td><td class="num">{int(r["n"])}</td></tr>'
        for _, r in scope.iterrows()] if not scope.empty else []
    scope_table = table(
        'Value factor regressed on own-region and transmission-region penetration together, '
        'year means removed',
        [('Technology', False), ('Own region', True), ('Transmission region', True),
         ('R&sup2;', True), ('n', True)], scope_rows)

    align_table = ''
    if not align.empty:
        p = align[align['year'] == 'pooled_year_fe']
        if not p.empty:
            piv = p.pivot(index='metric', columns='tech', values='r')
            techs_a = list(piv.columns)
            rows = [f'<tr><td><span class="eq">{m}</span></td>'
                    + ''.join(f'<td class="num">{_num(piv.loc[m, t])}</td>' for t in techs_a)
                    + '</tr>' for m in piv.index]
            align_table = table(
                'Correlation of each deployment measure with the relative value factor, '
                'pooled with year means removed',
                [('Measure', False)] + [(display_tech(t), True) for t in techs_a], rows)

    # ---- 06 cost factor components ----
    fig_comp = figure(output_dir, 'spatial_value_cost_decomp.png', n,
                      'Regional cost factor, actual against a composition-only index.',
                      'The national cost factor of new builds is a MW-weighted average over '
                      'regions. The composition series holds each region&rsquo;s cost at its own '
                      'MW-weighted mean across all years and lets only the regional weights move; '
                      'the within-region series is the ratio of the two. Indexed to the mean of the '
                      'first few build years, which are shaded.', order)
    n += 1 if fig_comp else 0
    comp_rows = [
        f'<tr>{tech_cell(r["tech"])}'
        f'<td class="num">{r["t_lo"]}&#8211;{r["t_hi"]}</td>'
        f'<td class="num">{_num(r["actual"])}</td>'
        f'<td class="num">{_num(r["compos"])}</td>'
        f'<td class="num">{_num(r["actual"] / r["compos"] if r["compos"] else np.nan)}</td></tr>'
        for _, r in comp.iterrows()] if not comp.empty else []
    comp_table = table(
        'Cost factor rise from the early build window to the late one',
        [('Technology', False), ('Years', True), ('Actual', True), ('Composition only', True),
         ('Within region', True)], comp_rows)

    # ---- 07 LVOE against LCOE ----
    fig_lvoe = figure(output_dir, 'lvoe_vs_lcoe.png', n,
                      'LVOE against the distribution of LCOE for capacity built each year.',
                      'Boxes are capacity-weighted percentiles of the model&rsquo;s lcoe output '
                      'over the supply-curve bins invested in that year; the dashed line is their '
                      'capacity-weighted mean. The solid line is weighted-average LVOE. Both sides '
                      'are per uncurtailed MWh.', order)
    fig_lvoe2 = figure(output_dir, 'lvoe_vs_lcoe_byyear.png', n + 1,
                       'LVOE against LCOE for each new-build bin, by model year.',
                       'One dot per class-region-bin the model built that year, for the same model '
                       'years as the map figures. x is the model&rsquo;s lcoe output divided by the '
                       'mandate multiplier, so it is the unforced cost; y is new-build LVOE from '
                       'valnew, which is per class and region and so shared by every bin of a class '
                       'in a region. Dot area is the bin&rsquo;s annual energy, chosen capacity times '
                       'gen_rsc, which reconciles to valnew&rsquo;s MWh; colour is the '
                       'region&rsquo;s penetration, uncurtailed generation over load. The solid line '
                       'is LVOE = force_mult times LCOE, the break-even at the cost the model optimised on, '
                       'and the dotted line is LVOE = LCOE. Each panel is scaled on its own, from the 98th percentile of its '
                       'own values. Only invested bins are shown, since the model writes lcoe '
                       'for those alone.', order)

    lvoe_rows = []
    if not lvoe.empty and 'lvoe_over_lcoe' in lvoe:
        for tech, g in lvoe.groupby('tech'):
            g = g.sort_values('year')
            lvoe_rows.append(
                f'<tr>{tech_cell(tech)}'
                f'<td class="num">{g["lvoe_over_lcoe"].min():.2f}</td>'
                f'<td class="num">{g["lvoe_over_lcoe"].median():.2f}</td>'
                f'<td class="num">{g["lvoe_over_lcoe"].max():.2f}</td>'
                f'<td class="num">{len(g)}</td></tr>')
    lvoe_table = table('Ratio of weighted-average LVOE to the capacity-weighted mean LCOE built',
                       [('Technology', False), ('Min', True), ('Median', True), ('Max', True),
                        ('Years', True)], lvoe_rows)

    fell_back = any(isinstance(o, tuple) for o in order)
    if embed_figures and not fell_back:
        packaging = (f'Figures are embedded at up to {embed_max_width}px wide; the full-size pngs '
                     f'are alongside this file.')
    elif embed_figures:
        packaging = ('Figures are referenced rather than embedded, because Pillow was not '
                     'available. This page only renders next to them.')
    else:
        packaging = 'Figures are referenced by filename. This page only renders next to them.'

    techs_str = ', '.join(display_tech(t) for t in core['tech'].unique())
    yr_lo, yr_hi = int(core['year'].min()), int(core['year'].max())
    scen = ', '.join(sorted(core['scenario'].unique()))

    def sec(num, title, *blocks):
        body = ''.join(b for b in blocks if b)
        return (f'<section><div class="shead"><div class="snum">{num}</div><h2>{title}</h2></div>'
                f'{body}</section>') if body else ''

    return f'''<title>{report_title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@500;600;700&family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&display=swap">
<style>{CSS}</style>
<div class="wrap">
<header>
  <div class="lbl">ReEDS &middot; value&#8211;cost factor analysis</div>
  <h1>{report_title}</h1>
  <p class="stand">Figures and tables produced by the value&#8211;cost factor pipeline, with a
  description of what each one plots. Numbers are computed from the tables written alongside this
  page, so re-running the report restates them.</p>
  <div class="meta"><span>{len(core["tech"].unique())} technologies</span>
    <span>{yr_lo}&#8211;{yr_hi}</span><span>{dollar_year}$/MWh</span>
    <span>scenarios: {scen}</span></div>
</header>

{sec('01', 'ReEDS marginal LCOE and the reV supply curve',
     '<div class="col"><p>The cost factor is the marginal cost of the next unit divided by the ATB '
     'base cost for the same year, net of the mandate ramp. This section places the ReEDS marginal '
     'LCOE, re-based onto the LCOE base year by that factor, on the reV supply curve the runs were '
     'built from. The additive re-basing using the LCOE adder is plotted in the companion figure '
     '<span class="eq">reeds_vs_rev.png</span>.</p></div>', fig1, rev_table, fig1b, curt_table)}

{sec('02', 'Value factor and value&#8211;cost factor by technology',
     '<div class="col"><p>For each technology the LCOE base is scaled until the value factor and '
     'value&#8211;cost factor fits share an intercept at zero market share, so the two curves start '
     'together. Under the power form the ratio of the fits reduces to '
     '<span class="eq">(1&minus;x)<sup>k<sub>VCF</sub> &minus; k<sub>VF</sub></sup></span>, so the '
     'exponent difference is the band width in the table below. Technologies whose data does not '
     'approach zero market share have that intercept extrapolated rather than measured, and the '
     'figure marks them.</p></div>', fig2, fit_table, decline_table, fig2b, fig2c)}

{sec('02b', 'Storage value factor and value&#8211;cost factor',
     '<div class="col"><p>Storage is drawn apart from the other technologies because its value '
     'factor exceeds one at low market share and its market share stops near 15%, so a shared pair '
     'of axis ranges spent most of its span on a corner of the plane that only storage occupies. '
     'The construction is unchanged; only the axes are its own. Storage remains in the fits table '
     'above, which has no axis to distort.</p></div>' '</p><p>The second figure reports the duration of the builds themselves, which the model chooses freely: power and energy capacity are separate investment variables, so duration is an outcome rather than an assumption.</p></div>', stor_fig, dur_fig, dur_table)}

{sec('02c', 'Gas-CC against the national natural gas supply curve',
     '<div class="col"><p>The runs hold natural gas prices static, which removes the cost-escalation '
     'channel a gas plant has through its own fuel: burning more gas raises its price. This section '
     'adds the national term of the model&rsquo;s default gas supply curve to the solved run. The '
     'correction is an estimate on a fixed solution rather than a re-solve, so it is an upper bound '
     'on the cost side - a re-solve would build less gas - while the linear coefficient is '
     'extrapolated well beyond the quantities it was calibrated on, which pushes the other way. '
     'Neither figure nor table is a model result.</p></div>', gas_fuel_fig, gas_fig, gas_decline_table, gas_table)}

{sec('02d', 'Capacity credit of new builds',
     '<div class="col"><p>The reserve-margin component of value per MW, expressed as a share of '
     'what a perfectly firm MW earns in the same place and year. It is the part of the value '
     'factor that firmness accounts for, so it is plotted against the same market-share axis as '
     'the curves above. The quantity is read from each technology&rsquo;s own forcing run and is '
     'only defined under the stress-period reserve margin '
     '(<span class="eq">GSw_PRM_CapCredit=0</span>); under the capacity-credit formulation ReEDS '
     'does not write val_resmarg for non-VRE and the section is skipped.</p></div>',
     cc_fig, cc_table, cc_cap_fig, cc_sc_fig, cc_sc_table,
     '<div class="col"><p>The figure below takes storage apart, because its credit is built differently from the others: a battery delivers no net energy over a stress period, so what it earns there is entirely the price spread between the hours it discharges in and the hours it charges in.</p></div>', arb_fig, arb_table)}

{sec('03', 'Log decomposition of the value&#8211;cost factor decline',
     '<div class="col"><p>Value&#8211;cost factor is the product of value factor and the reciprocal '
     'of cost factor, so <span class="eq">&minus;ln VCF = &minus;ln VF + &minus;ln(1/CF)</span> '
     'holds at every point with no fitting. The bars split the total log decline on that '
     'identity.</p></div>', fig3, share_table)}

{sec('04', 'Regional maps by model year',
     '<div class="col"><p>Value factors in these maps are divided by the national fleet value '
     'factor of the same year rather than by each region&rsquo;s own price, so the colour scale is '
     'comparable across years and the regional price, which is itself affected by deployment, is '
     'not divided back out.</p></div>' + map_figs)}

{sec('05', 'Regional value factor against penetration', fig_supp, supp_table,
     '<div class="col"><p>The table below enters own-region and transmission-region penetration in '
     'the same regression, which separates two regressors that are themselves correlated.</p></div>',
     scope_table, align_table)}

{sec('06', 'Regional cost factor: mix and within-region components', fig_comp, comp_table)}

{sec('07', 'LVOE against the LCOE of capacity built',
     '<div class="col"><p>The cost factor takes weighted-average LVOE as the marginal LCOE. This '
     'section places that quantity against the model&rsquo;s own LCOE outputs for the same '
     'builds.</p></div>', fig_lvoe, lvoe_table, fig_lvoe2)}

<section style="border-bottom:none">
  <footer>Generated by <code>valcostfac_report.py</code> from the figures and tables in this
  directory. Technologies: {techs_str}. All monetary values {dollar_year}$. {packaging}</footer>
</section>
</div>
'''


def make_report(valcostfac_core_path=valcostfac_core_path, output_dir=None):
    """Write the html report next to the figures it references."""
    if output_dir is None:
        output_dir = os.path.dirname(os.path.abspath(valcostfac_core_path))
    html = build_html(output_dir, valcostfac_core_path)
    path = os.path.join(output_dir, report_name)
    with open(path, 'w') as f:
        f.write(html)
    size = os.path.getsize(path)
    how = 'figures embedded' if embed_figures else 'figures referenced'
    unit = f'{size / 1048576:.1f} MB' if size > 1048576 else f'{size / 1024:.0f} kB'
    print(f'Wrote {path} ({unit}, {how})')
    return path


if __name__ == '__main__':
    make_report()
